### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by spencerbeggs** [brakmic/CarPool#1]
I get: `Error: Cannot find module '../src/core'`

Thanks for setting this demo up!

**Comment by brakmic** [comment]
You're welcome. 

The scripts in **tests** directory are merely demos. Being very busy with tracking Angular2 releases I abandoned this repo as a whole (it runs on an old Inferno version)

But if there's some interest I'd update the scripts.

Regards,

**Comment by spencerbeggs** [comment]
If there's a way for you to restore that missing file, I believe the tests would run just fine. Even if you don't plan to update this anymore, it might be nice to have it in a working state as it is a nice example of a basic Inferno setup.

**Comment by brakmic** [comment]
So, the updated version + tests are available now.

Regards,
